version: "3"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:5000"
    depends_on:
      - mysql-db
    networks:
      - my_network

  mysql-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: task_manager
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwerty
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - db-data:/var/lib/mysql

networks:
  my_network:

volumes:
  db-data:
